In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("Data/train.csv")

In [3]:
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
df.shape

(2000, 21)

In [5]:
df.isnull().any()

battery_power    False
blue             False
clock_speed      False
dual_sim         False
fc               False
four_g           False
int_memory       False
m_dep            False
mobile_wt        False
n_cores          False
pc               False
px_height        False
px_width         False
ram              False
sc_h             False
sc_w             False
talk_time        False
three_g          False
touch_screen     False
wifi             False
price_range      False
dtype: bool

In [6]:
df1=pd.read_csv("Data/test.csv")

In [7]:
df1.head()

id  battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0   1           1043     1          1.8         1  14       0           5   
1   2            841     1          0.5         1   4       1          61   
2   3           1807     1          2.8         0   1       0          27   
3   4           1546     0          0.5         1  18       1          25   
4   5           1434     0          1.4         0  11       1          49   

   m_dep  mobile_wt  ...  pc  px_height  px_width   ram  sc_h  sc_w  \
0    0.1        193  ...  16        226      1412  3476    12     7   
1    0.8        191  ...  12        746       857  3895     6     0   
2    0.9        186  ...   4       1270      1366  2396    17    10   
3    0.5         96  ...  20        295      1752  3893    10     0   
4    0.5        108  ...  18        749       810  1773    15     8   

   talk_time  three_g  touch_screen  wifi  
0          2        0             1     0  
1          7        1             0     0  
2         10        0             1     1  
3          7        1             1     0  
4          7        1             0     1  

[5 rows x 21 columns]

In [8]:
df1.isna().sum()

id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
dtype: int64

for c in df.columns:
    print (c,df[c].unique())

In [9]:
df1.columns[1:] == df.columns[:-1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [10]:
df_temp=pd.DataFrame(columns=['height','width'])

In [11]:
df_temp['height']=df['px_height']
df_temp['width']=df['px_width']

In [12]:
df_temp

height  width
0         20    756
1        905   1988
2       1263   1716
3       1216   1786
4       1208   1212
5       1004   1654
6        381   1018
7        512   1149
8        386    836
9       1137   1224
10       248    874
11       151   1005
12       607    748
13       344   1440
14       356    563
15       862   1864
16       984   1850
17       441    810
18       658    878
19       902   1064
20      1314   1854
21       974   1385
22       407    822
23       466    788
24       201   1245
25       291   1434
26       550    645
27       511   1075
28       187   1311
29      1171   1263
...      ...    ...
1970     675    742
1971     455    537
1972      42    807
1973    1196   1651
1974     503    986
1975    1694   1798
1976     306    558
1977     838    885
1978     291    651
1979     173   1219
1980    1017   1289
1981     698   1018
1982     610   1437
1983     223    737
1984     206   1167
1985    1457   1919
1986     742    999
1987     591    724
1988     347    957
1989     241    854
1990     743   1426
1991       4    743
1992     576   1809
1993     888   1099
1994     528   1416
1995    1222   1890
1996     915   1965
1997     868   1632
1998     336    670
1999     483    754

[2000 rows x 2 columns]

In [13]:
df=df.rename(columns={'blue':'bluetooth','fc':'front_cam_mp','sc_h':'screen_ht','sc_w':'screen_wt'})

In [14]:
df=df.rename(columns={'pc':'back_cam_mp'})

In [15]:
df=df.drop(columns=['m_dep','mobile_wt','px_height','px_width'])

In [16]:
df.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam_mp  four_g  \
0            842          0          2.2         0             1       0   
1           1021          1          0.5         1             0       1   
2            563          1          0.5         1             2       1   
3            615          1          2.5         0             0       0   
4           1821          1          1.2         0            13       1   

   int_memory  n_cores  back_cam_mp   ram  screen_ht  screen_wt  talk_time  \
0           7        2            2  2549          9          7         19   
1          53        3            6  2631         17          3          7   
2          41        5            6  2603         11          2          9   
3          10        6            9  2769         16          8         11   
4          44        2           14  1411          8          2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1

In [17]:
df.shape

(2000, 17)

In [18]:
df1=df1.rename(columns={'blue':'bluetooth','fc':'front_cam_mp','sc_h':'screen_ht','sc_w':'screen_wt','pc':'back_cam_mp'})

In [19]:
df1=df1.drop(columns=['m_dep','mobile_wt','px_height','px_width','id'])

In [20]:
df1.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam_mp  four_g  \
0           1043          1          1.8         1            14       0   
1            841          1          0.5         1             4       1   
2           1807          1          2.8         0             1       0   
3           1546          0          0.5         1            18       1   
4           1434          0          1.4         0            11       1   

   int_memory  n_cores  back_cam_mp   ram  screen_ht  screen_wt  talk_time  \
0           5        3           16  3476         12          7          2   
1          61        5           12  3895          6          0          7   
2          27        3            4  2396         17         10         10   
3          25        8           20  3893         10          0          7   
4          49        6           18  1773         15          8          7   

   three_g  touch_screen  wifi  
0        0             1     0  
1        1             0     0  
2        0             1     1  
3        1             1     0  
4        1             0     1

In [21]:
df1.shape

(1000, 16)

In [22]:
for c in df.columns:
    print(df[c].value_counts())
    

1589    6
618     6
1872    6
1379    5
1310    5
1063    5
832     5
1414    5
1413    5
1807    5
1512    5
1083    5
772     5
1715    5
1330    5
1949    5
504     5
1068    5
600     4
1002    4
1762    4
586     4
623     4
826     4
825     4
1617    4
1154    4
1035    4
1454    4
808     4
       ..
1029    1
1645    1
1031    1
1644    1
1036    1
1038    1
1641    1
1638    1
1635    1
1045    1
1046    1
1634    1
1633    1
1632    1
1616    1
1056    1
1630    1
1058    1
1061    1
1627    1
1625    1
1064    1
1623    1
1070    1
1071    1
1072    1
1073    1
1074    1
1075    1
1998    1
Name: battery_power, Length: 1094, dtype: int64
0    1010
1     990
Name: bluetooth, dtype: int64
0.5    413
2.8     85
2.3     78
1.6     76
2.1     76
2.5     74
0.6     74
1.4     70
1.3     68
2.0     67
1.5     67
1.9     65
0.7     64
1.8     62
2.9     62
1.0     61
1.7     60
2.2     59
0.8     58
2.4     58
0.9     58
1.2     56
2.7     55
2.6     55
1.1     51
3.0     28
Name: 

In [23]:
df['battery_power'].describe()

count    2000.000000
mean     1238.518500
std       439.418206
min       501.000000
25%       851.750000
50%      1226.000000
75%      1615.250000
max      1998.000000
Name: battery_power, dtype: float64

In [24]:
df['bluetooth'].unique()

array([0, 1], dtype=int64)

In [25]:
df['clock_speed'].unique()

array([2.2, 0.5, 2.5, 1.2, 1.7, 0.6, 2.9, 2.8, 2.1, 1. , 0.9, 1.1, 2.6,
       1.4, 1.6, 2.7, 1.3, 2.3, 2. , 1.8, 3. , 1.5, 1.9, 2.4, 0.8, 0.7])

In [26]:
df['dual_sim'].value_counts()

1    1019
0     981
Name: dual_sim, dtype: int64

In [27]:
df['front_cam_mp'].unique()

array([ 1,  0,  2, 13,  3,  4,  5,  7, 11, 12, 16,  6, 15,  8,  9, 10, 18,
       17, 14, 19], dtype=int64)

In [28]:
df['four_g'].value_counts()

1    1043
0     957
Name: four_g, dtype: int64

In [29]:
df['int_memory'].describe()

count    2000.000000
mean       32.046500
std        18.145715
min         2.000000
25%        16.000000
50%        32.000000
75%        48.000000
max        64.000000
Name: int_memory, dtype: float64

In [30]:
df['n_cores'].value_counts()

4    274
7    259
8    256
2    247
5    246
3    246
1    242
6    230
Name: n_cores, dtype: int64

In [31]:
df['back_cam_mp'].describe()

count    2000.000000
mean        9.916500
std         6.064315
min         0.000000
25%         5.000000
50%        10.000000
75%        15.000000
max        20.000000
Name: back_cam_mp, dtype: float64

In [32]:
df['ram'].describe()

count    2000.000000
mean     2124.213000
std      1084.732044
min       256.000000
25%      1207.500000
50%      2146.500000
75%      3064.500000
max      3998.000000
Name: ram, dtype: float64

In [33]:
df['screen_ht'].unique()

array([ 9, 17, 11, 16,  8, 13, 19,  5, 14, 18,  7, 10, 12,  6, 15],
      dtype=int64)

In [34]:
df['screen_wt'].unique()

array([ 7,  3,  2,  8,  1, 10,  9,  0, 15, 13,  5, 11,  4, 12,  6, 17, 14,
       16, 18], dtype=int64)

In [35]:
df['talk_time'].describe()

count    2000.000000
mean       11.011000
std         5.463955
min         2.000000
25%         6.000000
50%        11.000000
75%        16.000000
max        20.000000
Name: talk_time, dtype: float64

In [36]:
df['three_g'].value_counts()

1    1523
0     477
Name: three_g, dtype: int64

In [37]:
df['touch_screen'].value_counts()

1    1006
0     994
Name: touch_screen, dtype: int64

In [38]:
df['four_g'].value_counts()

1    1043
0     957
Name: four_g, dtype: int64

In [39]:
df['wifi'].value_counts()

1    1014
0     986
Name: wifi, dtype: int64

In [40]:
df['price_range'].value_counts()

3    500
2    500
1    500
0    500
Name: price_range, dtype: int64

In [41]:
df=df.drop(columns=['talk_time'])
df1=df1.drop(columns=['talk_time'])

In [42]:
df['clock_speed'].describe()

count    2000.000000
mean        1.522250
std         0.816004
min         0.500000
25%         0.700000
50%         1.500000
75%         2.200000
max         3.000000
Name: clock_speed, dtype: float64

In [43]:
bin_labels = ['low', 'mid', 'high']
df['clock_cat'] = pd.qcut(df['ram'],
                              q=[0, 1, 2, 3,4,5,6],
                              labels=bin_labels)

IndexError: index 3998 is out of bounds for axis 0 with size 2000

In [44]:
df['clock_speed']=pd.cut(df['clock_speed'],bins=[0,1,2,3],labels=['low','mid','high'])



In [45]:
df.head()

battery_power  bluetooth clock_speed  dual_sim  front_cam_mp  four_g  \
0            842          0        high         0             1       0   
1           1021          1         low         1             0       1   
2            563          1         low         1             2       1   
3            615          1        high         0             0       0   
4           1821          1         mid         0            13       1   

   int_memory  n_cores  back_cam_mp   ram  screen_ht  screen_wt  three_g  \
0           7        2            2  2549          9          7        0   
1          53        3            6  2631         17          3        1   
2          41        5            6  2603         11          2        1   
3          10        6            9  2769         16          8        1   
4          44        2           14  1411          8          2        1   

   touch_screen  wifi  price_range  
0             0     1            1  
1             1     0            2  
2             1     0            2  
3             0     0            2  
4             1     0            1

In [ ]:
df=df.drop(columns=['clock_cat'])

In [46]:
level_map={'low':0,'mid':1,'high':2}
df['clock_speed']=df['clock_speed'].replace(level_map)

In [47]:
df.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam_mp  four_g  \
0            842          0            2         0             1       0   
1           1021          1            0         1             0       1   
2            563          1            0         1             2       1   
3            615          1            2         0             0       0   
4           1821          1            1         0            13       1   

   int_memory  n_cores  back_cam_mp   ram  screen_ht  screen_wt  three_g  \
0           7        2            2  2549          9          7        0   
1          53        3            6  2631         17          3        1   
2          41        5            6  2603         11          2        1   
3          10        6            9  2769         16          8        1   
4          44        2           14  1411          8          2        1   

   touch_screen  wifi  price_range  
0             0     1            1  
1             1     0            2  
2             1     0            2  
3             0     0            2  
4             1     0            1

In [ ]:
a=df[df.ram >= 800 and df.ram <= 1200].value_counts()

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from sklearn import preprocessing

In [ ]:
df['ram'].plot(kind='density')

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer

In [ ]:
pd.cut(df['ram'],bins=[0,512,1024,1536,2048,2560,3072,3539,4051],labels=['0','1','2','3','4','5','6','7']).value_counts()

In [ ]:
ram = df[['ram']]
print(ram)

In [ ]:
ram = ram.values.reshape(-1,1)

In [ ]:
from sklearn.preprocessing import KBinsDiscretizer  
est = KBinsDiscretizer(n_bins=8, encode='onehot', strategy='kmeans')
Xt2 = est.fit_transform(ram)

In [ ]:
ram2 = pd.DataFrame(Xt, index = df.index, columns = ['ram_binned'])
ram2

In [ ]:
ram2['ram'].value_counts()

In [ ]:
df2 = df.copy()

In [ ]:
df.shape

In [ ]:
df = df.merge(ram2, left_index = True, right_index = True)
df.shape

In [ ]:
df[df['ram_binned'] == 1.0]['ram'].describe()